# Welcome to Jekyll!

# Website settings
title: A Well Charted Path
description: We are two people traveling a well charted path to 34 countries across 6 continents over 11 months.
keywords: travel, RTW
baseurl:  # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://site.awellchartedpath.com  # url should be 'http://<github_username>.github.io/homepage' as before
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before
permalink: /blog/:year/:month/:title/

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Amy   # Be used at blog posts' author.
  first_name: Amy  # Be used at index page about me section.
  last_name:   # Be used at index page about me section.
  github_username:   # Leave blank if you don't have now
  instagram_id: wellchartedpath # Leave blank if you don't have now
  linkedin_id:  # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username: WellChartedPath  # Leave blank if you don't have now
  email:   # Leave blank if you don't have now
  cv:   # A online CV can be printed as PDF, leave blank if you don't have now
  desc: Introduce myself will be here.  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
   id: UA-100811992-1

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
